eal# yaml-language-server: $schema=https://json.schemastore.org/github-workflow-template.json

name: Run hyperfine benchmark

on:
  workflow_call:
    inputs:
      LOCATION:
        required: true
        type: string

jobs:
  hyperfine:
    steps:
      - uses: actions/checkout@v4
      - name: configuration
        run: |
          echo "LOCATION: ${{ inputs.LOCATION }}"
          echo "COREPACK_ENABLE_STRICT: ${{ env.COREPACK_ENABLE_STRICT }}"
          echo "COREPACK_ENABLE_AUTO_PIN: ${{ env.COREPACK_ENABLE_AUTO_PIN }}"
          echo "YARN_ENABLE_IMMUTABLE_INSTALLS: ${{ env.YARN_ENABLE_IMMUTABLE_INSTALLS }}"
      - name: run
        run: |
          cd ${{ inputs.LOCATION }}
          hyperfine --export-json --warmup 3 --runs 10 -i --prepare ' \
              rm -rf ./node_modules/; \
              rm -rf .npm*; \
              rm -rf .yarn*; \
              rm -rf .pnp*; \
              rm -rf .vlt*; \
              rm -rf package-lock.json; \
              rm -rf yarn.lock; \
              rm -rf pnpm-lock.yaml; \
              rm -rf vlt-lock.json; \
              rm -rf bun.lockb; \
              rm -rf deno.lock; \
              npm cache clean --force; \
              yarn@1 cache clean --all; \
              yarn@latest cache clean --all; \
              pnpm cache delete *; \
              rm -rf $(vlt config get cache); \
              rm -rf $(bun pm cache); \
              deno clean; \
              npm pkg delete packageManager; \
              git add .; \
              git stash' \
            'npm install --no-audit --no-fund' \
            'corepack yarn@1 install' \
            'corepack yarn@latest install' \
            'corepack pnpm@latest install' \
            'vlt install' \
            'bun install' \
            'deno install --allow-scripts'
